version: '3.5'

services:
  node:
    build: .
    image: NodeBBCN.azurecr.io/nodebb
    restart: unless-stopped
    depends_on:
      - proxy
    expose:
      - 4567

  proxy:
    build: ./nginx
    image: NodeBBCN.azurecr.io/proxy
    restart: unless-stopped
    ports:
      - 80:80
    expose:
      - 80
