version: '3.5'

services:
  node:
    build: .
    restart: unless-stopped
    depends_on:
      - proxy
    expose:
      - 4567

  proxy:
    build: ./nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
