version: '3.5'

services:
  node:
    build: .
    image: NodeBBCN.azurecr.io/nodebb
    restart: unless-stopped
    depends_on:
      - search
      - proxy
    expose:
      - 4567

  search:
    build: ./solr
    image: NodeBBCN.azurecr.io/search
    restart: unless-stopped
    expose:
      - 8983

  proxy:
    build: ./nginx
    image: NodeBBCN.azurecr.io/proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
