version: '3.5'

services:
  node:
    build: .
    image: NodeBB.azurecr.io/nodebb
    restart: unless-stopped
    depends_on:
      - search
      - proxy
    expose:
      - 4567

  search:
    image: solr:alpine
    restart: unless-stopped
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - nodebb
    expose:
      - 8983

  proxy:
    build: ./nginx
    image: NodeBB.azurecr.io/proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
